/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Main;

import Controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author THIEN
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setTitle("Quan ly tu thien");
        
        ChuyenManHinhController controller = new ChuyenManHinhController(contentPanel);
        controller.setView(dashboardBtn);
        
        List<DanhMucBean> danhMuc = new ArrayList<>();
        danhMuc.add(new DanhMucBean("dashboard", dashboardBtn));
        danhMuc.add(new DanhMucBean("donors_receivers", donorsReceiversBtn));
        danhMuc.add(new DanhMucBean("donations_distributions", DonationsDistributionsBtn));
        danhMuc.add(new DanhMucBean("events", eventsBtn));
        controller.setEvent(danhMuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        eventsBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        donorsReceiversBtn = new javax.swing.JButton();
        DonationsDistributionsBtn = new javax.swing.JButton();
        logoPanel = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1180, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(0, 102, 204));
        sideBarPanel.setAutoscrolls(true);
        sideBarPanel.setPreferredSize(new java.awt.Dimension(250, 700));
        sideBarPanel.setRequestFocusEnabled(false);
        sideBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutBtn.setText("Log out");
        logoutBtn.setToolTipText("");
        logoutBtn.setBorder(null);
        sideBarPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 130, 30));

        eventsBtn.setBackground(new java.awt.Color(204, 255, 255));
        eventsBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        eventsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources.Images/calendar-star.png"))); // NOI18N
        eventsBtn.setText("Events");
        eventsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eventsBtn.setIconTextGap(12);
        eventsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsBtnActionPerformed(evt);
            }
        });
        sideBarPanel.add(eventsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 50));

        dashboardBtn.setBackground(new java.awt.Color(204, 255, 255));
        dashboardBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources.Images/dashboard_1.png"))); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardBtn.setIconTextGap(12);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        sideBarPanel.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, 50));

        donorsReceiversBtn.setBackground(new java.awt.Color(204, 255, 255));
        donorsReceiversBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        donorsReceiversBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources.Images/users-alt.png"))); // NOI18N
        donorsReceiversBtn.setText("Donors & Receivers");
        donorsReceiversBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        donorsReceiversBtn.setIconTextGap(12);
        donorsReceiversBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorsReceiversBtnActionPerformed(evt);
            }
        });
        sideBarPanel.add(donorsReceiversBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 50));

        DonationsDistributionsBtn.setBackground(new java.awt.Color(204, 255, 255));
        DonationsDistributionsBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DonationsDistributionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources.Images/people-arrows-left-right.png"))); // NOI18N
        DonationsDistributionsBtn.setText("Donations & Distribution");
        DonationsDistributionsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DonationsDistributionsBtn.setIconTextGap(12);
        DonationsDistributionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonationsDistributionsBtnActionPerformed(evt);
            }
        });
        sideBarPanel.add(DonationsDistributionsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 50));

        logoPanel.setBackground(new java.awt.Color(102, 153, 255));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        appNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        appNameLabel.setText("CharmanApp");
        logoPanel.add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        sideBarPanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        getContentPane().add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        contentPanel.setBackground(new java.awt.Color(245, 245, 245));
        contentPanel.setPreferredSize(new java.awt.Dimension(900, 700));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 890, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventsBtnActionPerformed

    private void donorsReceiversBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorsReceiversBtnActionPerformed

    }//GEN-LAST:event_donorsReceiversBtnActionPerformed

    private void DonationsDistributionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonationsDistributionsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonationsDistributionsBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed

    }//GEN-LAST:event_dashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DonationsDistributionsBtn;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton donorsReceiversBtn;
    private javax.swing.JButton eventsBtn;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel sideBarPanel;
    // End of variables declaration//GEN-END:variables
}
