/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Main;

import ConnectDB.connect_db;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THIEN
 */
public class DonorsReceiversPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorsReceiversPanel
     */
    public DonorsReceiversPanel() {
        initComponents();
        
        try {
            Connection conn = connect_db.getConnection();
            Statement st = conn.createStatement();
            String query = "SELECT * FROM DONOR";
            ResultSet rs = st.executeQuery(query);
            
            DefaultTableModel model = (DefaultTableModel) jXTable1.getModel();
            String id, name, gender, email, phone, score;
            while (rs.next()) {
                id = rs.getString(1);
                name = rs.getString(2);
                gender = rs.getString(3);
                email = rs.getString(7);
                phone = rs.getString(4);
                score = rs.getString(8);
                String[] row = {id, name, gender, score, phone, email};
                model.addRow(row);
            }
            st.close();
            conn.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorsReceiversPanel = new javax.swing.JTabbedPane();
        donorsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jButton6 = new javax.swing.JButton();
        receiversPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        donorsReceiversPanel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        donorsPanel.setLayout(new java.awt.BorderLayout());

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Score", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jXTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jXTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jXTable1);

        donorsPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("Add donor");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        donorsPanel.add(jButton6, java.awt.BorderLayout.PAGE_START);

        donorsReceiversPanel.addTab("Donors", donorsPanel);

        javax.swing.GroupLayout receiversPanelLayout = new javax.swing.GroupLayout(receiversPanel);
        receiversPanel.setLayout(receiversPanelLayout);
        receiversPanelLayout.setHorizontalGroup(
            receiversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        receiversPanelLayout.setVerticalGroup(
            receiversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        donorsReceiversPanel.addTab("Receivers", receiversPanel);

        add(donorsReceiversPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AddDonor addDonor = new AddDonor();
        donorsPanel.remove(jXTable1);
        donorsPanel.add(addDonor, BorderLayout.CENTER);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel donorsPanel;
    private javax.swing.JTabbedPane donorsReceiversPanel;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JPanel receiversPanel;
    // End of variables declaration//GEN-END:variables
}
