/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Main;

import ConnectDB.connect_db;
import Controller.DonorController;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THIEN
 */
public class DonorsReceiversPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorsReceiversPanel
     */
    public DonorsReceiversPanel() {
        initComponents();
        
        DonorController controller = new DonorController(donorViewPanel, donorAddBtn, donorSearchTF);
        controller.setDataModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorsReceiversPanel = new javax.swing.JTabbedPane();
        donorsPanel = new javax.swing.JPanel();
        donorAddBtn = new javax.swing.JButton();
        donorSearchTF = new javax.swing.JTextField();
        donorViewPanel = new javax.swing.JPanel();
        receiversPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        donorsReceiversPanel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        donorsPanel.setPreferredSize(new java.awt.Dimension(900, 700));
        donorsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorAddBtn.setBackground(new java.awt.Color(153, 204, 255));
        donorAddBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        donorAddBtn.setText("Add donor");
        donorAddBtn.setBorder(null);
        donorAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorAddBtnActionPerformed(evt);
            }
        });
        donorsPanel.add(donorAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 100, 30));
        donorsPanel.add(donorSearchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 30));

        javax.swing.GroupLayout donorViewPanelLayout = new javax.swing.GroupLayout(donorViewPanel);
        donorViewPanel.setLayout(donorViewPanelLayout);
        donorViewPanelLayout.setHorizontalGroup(
            donorViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        donorViewPanelLayout.setVerticalGroup(
            donorViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        donorsPanel.add(donorViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 820, 450));

        donorsReceiversPanel.addTab("Donors", donorsPanel);

        javax.swing.GroupLayout receiversPanelLayout = new javax.swing.GroupLayout(receiversPanel);
        receiversPanel.setLayout(receiversPanelLayout);
        receiversPanelLayout.setHorizontalGroup(
            receiversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );
        receiversPanelLayout.setVerticalGroup(
            receiversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        donorsReceiversPanel.addTab("Receivers", receiversPanel);

        add(donorsReceiversPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void donorAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorAddBtnActionPerformed
        AddDonor addDonor = new AddDonor();
//        donorsPanel.remove(jXTable1);
//        donorsPanel.add(addDonor, BorderLayout.CENTER);   // TODO add your handling code here:
    }//GEN-LAST:event_donorAddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donorAddBtn;
    private javax.swing.JTextField donorSearchTF;
    private javax.swing.JPanel donorViewPanel;
    private javax.swing.JPanel donorsPanel;
    private javax.swing.JTabbedPane donorsReceiversPanel;
    private javax.swing.JPanel receiversPanel;
    // End of variables declaration//GEN-END:variables
}
